### ISSUE TITLE
Incompatible with WYSIWYG CKEditor 

### ISSUE THREAD

**Issue by zachharkey** [mpezzi/bootstrap#1]
First, let me say thanks for the great work. 

I followed the instructions and installed the base theme, then created a new custom sub theme based on the starterkit. But I can't get the WYSIWYG module to load CKEditor.

I get the following error:

wysiwyg.js:237ReferenceError: Can't find variable: jQuery

... it does work if I move all the scripts in html.tpl.php to the head.

What do you think about using the jquery_update module to use jQuery 1.7? Evidently 7.x-2.x-dev branch is now on jQuery 1.7 (It provides a selection box for choosing 1.5 or 1.7 in the performance menu, i.e., same menu as clear cache button and cache / aggregation settings.)

**Comment by mpezzi** [comment]
Thanks for the help, much appreciated!
