### ISSUE TITLE
Contribute to http://drupal.org/project/twitter_bootstrap?

### ISSUE THREAD

**Issue by gagarine** [mpezzi/bootstrap#2]
Hi,

I like your work. I think it will make sens to merge with http://drupal.org/project/twitter_bootstrap to avoid duplication of effort. The owners of the repository will certainly give you an write access if you ask.

Their is a lot of ugly things in http://drupal.org/project/twitter_bootstrap but it should not take long to merge both project.

**Comment by mpezzi** [comment]
Yeah, I noticed there have been some other bootstrap implementations in Drupal, perhaps we should start looking to getting them all merge in to one über project.
- https://github.com/Lullabot/lullabot_bootstrap
- https://github.com/zachseifts/drupal_bootstrap

**Comment by gagarine** [comment]
Yep, I open the issue on DO http://drupal.org/node/1594508
