### ISSUE TITLE
Superfluous Nav-settings

### ISSUE THREAD

**Issue by fixed** [mpezzi/bootstrap#4]
Hey, 

first I wanted to thank you for this great Bootstrap Drupal wrapper! Nice work :)

I wonder though why you implemented those nav-switches in the theme settings. I mean, it is nice to see the different bootstrap elements in action but their behaviour is rather confusing. It seems to me that `bootstrap_nav` as well as `bootstrap_nav_sub` should not be used at the same time since both of them contain the same information. This could be changed in a subtheme of course, but it why do it in the first place? Additionally, the output of `bootstrap_nav_user` setting seems to be different when `bootstrap_nav` is activated. 

Generally speaking, having a few settings available is a good thing, I believe. However, the Nav-settings are kinda useless at this point. I suggest to provide a subtheme that uses the sub-nav instead of the top-nav and remove both the switches (nav and nav_sub). That way the base theme becomes a bit simpler and developers can still see how the subnav markup looks like.  I'd even go a bit further and make the basetheme exactly like the bootstrap docs example, i.e. top nav bar, jumbotron page-titles (instead of jumbotron site-name), subnav for the primary-tasks, tabs for the secondary, and so on ..

What do you think?

**Comment by mpezzi** [comment]
The navigation was thrown together as I was using this theme to quick build out some client projects, so it could definitely use some work.

Ultimately what I'd like to see is different types of "bootstrap" menus and you can choose which one is visible and which menu will populate it.

**Comment by mpezzi** [comment]
The navigation has been cleaned up a bit, most of the logic is actually inside of the page.tpl.php now. So you can easily change which menu shows up and can toggle which navigation components are visible in the theme settings page or info file.

I like your idea of creating multiple starter kits for different layout configurations.

**Comment by fixed** [comment]
Sounds interesting, I will definitely be back after my current internship!

**Comment by fixed** [comment]
Thanks for making all the changes. Looks definitely better now.
I'll give you more feedback after a deeper test-drive

**Comment by mpezzi** [comment]
Nice! We'll open up new issues for feature requests. Cheers!
